server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marcura
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

fixer:
  io:
    api:
      url: http://data.fixer.io/api/latest?access_key=686269be74f6cf52c86ed22923f864f9

springdoc:
  swagger-ui:
    path: /swagger-ui.html
